version: "3.1"

#volumes:
#  postgres-data: ~

services:
  app:
    build:
      context: .
      args:
        UID: ${DEV_UID}
    volumes:
      - ./project:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${COMPOSER_HOME}:/home/dev/.composer
      - ${SSH_DIR}:/home/dev/.ssh
    environment:
      - COMPOSER_HOME=/home/dev/.composer
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - XDEBUG_CONFIG
#    links:
#      - db

  nginx:
    image: nginx:alpine
    ports:
      - ${APP_HOST_PORT}:80
    links:
      - app
    volumes:
      - ./project:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf

#  db:
#    image: postgres:alpine
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - ${DATABASE_HOST_PORT}:5432
#    environment:
#      POSTGRES_USER:     'dev'
#      POSTGRES_PASSWORD: 'dev'